### ISSUE TITLE
请教代码的几处错误

### ISSUE THREAD

**Issue by erichuazhou** [Alibaba-NLP/StructuralKD#4]
1、flair/models/fintune_sequence_tagger.py里面有明显的错误
(1) 119行
![image](https://user-images.githubusercontent.com/44012390/221725195-1e261fc6-9119-4e85-9b15-4ec2e8141f16.png)
(2) 相当多的函数未定义
286行，328行，333行
是否ParallelSequenceTagger这个功能就没有实现过

2、Readme里面的主函数是 train_with_teacher.py
![image](https://user-images.githubusercontent.com/44012390/221725676-f2c93c03-dc3a-4e1a-9ea1-8b41ca07c0eb.png)
但是整个代码仓库中，只有train.py
是否是笔误？

谢谢。
@wangxinyu0922 @yanzhh @JZXXX

**Comment by wangxinyu0922** [comment]
fintune_sequence_tagger.py和ParallelSequenceTagger不会调用，你不需要在意。代码只会调用sequence_tagger_model.py。

train_with_teacher.py是笔误，我会修正。
