### ISSUE TITLE
想请教几个代码实现的问题

### ISSUE THREAD

**Issue by erichuazhou** [Alibaba-NLP/StructuralKD#5]
想请教几个代码实现的问题
1、主函数train.py中，有 "----parse"，请问这个指的是去parse自己的训练集吗？
2、在teacher模型的yaml中(multi_bert_origflair_300epoch_2000batch_0.1lr_256hidden_en_monolingual_crf_sentloss_10patience_baseline_nodev_ner0.yaml)，也有"teachers"项，这应该是没用上吧？
3、在student模型的yaml中(en_crf_ner.yaml)，有以下几个问题：
3.1 在已经有了"teachers"项的情况下，”"professors"项起什么作用的？
3.2 "distill_crf: false"项表示对是在distillation过程中不对crf进行distillation吗？？
3.3 "distill_exact: true"项指的是啥？
3.4 "crf_attention: false"项，crf_attention指的是什么？
3.5 "dropout: 0.0"貌似不太合理？

谢谢。
@wangxinyu0922 @yanzhh @JZXXX

**Comment by wangxinyu0922** [comment]
1. parse是指在无标注数据上进行预测，如果不需要无标注预测那么就用不上
2. 没用上
3. 1 没有用，无视即可
3.2 distill_crf是top k KD
3.3 distill exact就是本文提出的exact KD方法，针对序列标注的
3.4 weighted top K
3.5 dropout这项在模型里有别的设定，这个只控制了其中一个dropout

可以先跟着代码run一遍，有很多问题根据代码的pipeline也大概能确定

**Comment by erichuazhou** [comment]
谢谢解惑。因为wrapper代码太多了。

**Comment by erichuazhou** [comment]
发现另外一个问题：
finetune_trainer.py的resort()函数中1985行：
![image](https://user-images.githubusercontent.com/44012390/223002619-5f4ffe75-7805-4784-9189-b177123c7df6.png)
这会导致长度=1的句子，其teacher模型训练得到的posterior，没有正确的传递给新的new_posterior。
好奇问一下，如果保持teacher计算targets的batch和当前的batch保持一样，是不是就没有resort()这一步骤了。谢谢。
@wangxinyu0922 @yanzhh @JZXXX

**Comment by wangxinyu0922** [comment]
resort只是重新shuffle句子而已，如果不shuffle就不会调用

**Comment by erichuazhou** [comment]
感谢。
