### ISSUE TITLE
请教下FastSequenceTagger的_score_sentence()的实现问题

### ISSUE THREAD

**Issue by erichuazhou** [Alibaba-NLP/StructuralKD#6]
感觉实现的比较复杂，有点看不懂里面的逻辑。
既然SequenceTagger已经实现了_score_sentence()，为什么还是用另外一种方式实现呢？或者说新的实现有一些其它的作用？谢谢。
@wangxinyu0922 @yanzhh @JZXXX

**Comment by wangxinyu0922** [comment]
新的实现走的是并行计算的方式，按理会比原本的for循环快

**Comment by erichuazhou** [comment]
感谢！
